[project]
name = "room-reservation-app"
version = "0.1.0"
description = "Веб-сервис для автоматизации бронирования переговорных комнат в коворкинге"
authors = [
    {name = "Nikita Lutskii",email = "nikitalut@yandex.ru"}
]
requires-python = ">=3.11"
dependencies = [
    "fastapi (>=0.139.2,<0.140.0)",
    "uvicorn (>=0.51.0,<0.52.0)",
    "sqlalchemy (>=2.0.51,<3.0.0)",
    "pydantic (>=2.13.4,<3.0.0)",
    "pydantic-settings (>=2.14.2,<3.0.0)",
    "psycopg2 (>=2.9.12,<3.0.0)",
    "python-jose (>=3.5.0,<4.0.0)",
    "bcrypt (>=5.0.0,<6.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "black (>=26.5.1,<27.0.0)",
    "flake8 (>=7.3.0,<8.0.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-mock (>=3.15.1,<4.0.0)",
    "httpx2 (>=2.7.0,<3.0.0)"
]

[tool.poetry]
packages = [{ include = "app" }]

[tool.black]
target-version = ['py311']
line-length = 79

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = [
  "-vv",
  "--import-mode=importlib"
]